### ISSUE TITLE
clean up ourstory.html

### ISSUE THREAD

**Issue by gc824** [gc824/PizzaParty#12]
Can you clean up the ourstory.html: 

- check spellings
- img should be in image folder
- line #22 <iframe> should be in css file

**Comment by billythakidd04** [comment]
@gc824 an iframe cannot go into css. I think you're referring to the width height things on images was talking about the other day. All properties of an iframe need to remain contained in the iframe.

**Comment by rbaia28** [comment]
This was closed previously by @gc824
