### ISSUE TITLE
sticky heading

### ISSUE THREAD

**Issue by rbaia28** [gc824/PizzaParty#13]
Gagan creating smaller logo, linking back to main page with <a href, and deploying code to make logo sticky with nav bar

**Comment by billythakidd04** [comment]
this needs to be assigned. What do you mean by 'make logo sticky with nav bar'?

**Comment by rbaia28** [comment]
My plan was to include our logo and have it stay left justified in line with the navbar but have the navbar and the logo "sticky" to stay in the head of the page across the site. 

Orginal Plan was this:
Using this https://css-tricks.com/how-to-create-a-shrinking-header-on-scroll-without-javascript/

Now planning on bootstraps

**Comment by billythakidd04** [comment]
need a reason it was closed.
