### ISSUE TITLE
Becca handling main CSS page

### ISSUE THREAD

**Issue by rbaia28** [gc824/PizzaParty#7]
cancelled

**Comment by billythakidd04** [comment]
@rbaia28 there's no description to this ticket. What needs to be done? Give some more context and specifics...

**Comment by billythakidd04** [comment]
Also, if this is Becca's ticket, assign Becca to it.

**Comment by rbaia28** [comment]
Whoops. That was me. I will adjust!

**Comment by rbaia28** [comment]
Gagan taking lead on CSS for PizzaParty

**Comment by billythakidd04** [comment]
There is _still_ no description for this ticket....
